### PR TITLE
feat(batchDelete): batchDelete lambda handler

### PR DESCRIPTION
**Pull request by kschelonka**
## Goal

Add lambda code for invoking batchDelete endpoint on List API, through SQS message batches
Reports partial failures/successes.

## I'd love feedback/perspectives on:
- any

## Implementation Decisions
- Spec tests only for this, e2e has diminishing returns

## References

Jira ticket:
* https://getpocket.atlassian.net/browse/INFRA-569

### CODE REVIEW

**Review by jpetto — APPROVED** [review]
lgtm! i'm not exactly sure why spec tests are failing on imports - maybe you need to bump/clear circle cache for that job?

**Comment by kschelonka** [comment]
> lgtm! i'm not exactly sure why spec tests are failing on imports - maybe you need to bump/clear circle cache for that job?

I think it's because the spec tests were running for the whole api and not specifically the lambda sub-project (didn't install the lambda dependencies). I just tried to push an update, may take a few attempts 😅

**Review by jpetto — APPROVED** [review]
the joys of CI 🙃

**Review by Herraj — APPROVED** [review]
🚀

**Pull request merged**
